multiformats/rust-cid

.gitignore
.travis.yml
Cargo.toml
README.md
src/lib.rs
tests/lib.rs

Depends on https://github.com/multiformats/rust-multibase/pull/2 and https://github.com/OrKoN/base-x-rs/pull/1

[WIP] Implement

---

Cargo.toml
src/lib.rs

un-try! and fixed errors

---

Cargo.toml

Follow-up of https://github.com/multiformats/rust-multihash/pull/19

Upgrade multihash to 0.7

---

Cargo.toml
README.md
src/codec.rs
src/error.rs
src/lib.rs
src/to_cid.rs
src/version.rs
tests/lib.rs

...in preparation to some other changes

Move to the 2018 edition

---

Cargo.toml
src/lib.rs
tests/lib.rs

This PR updates the code to the not-yet released version of multihash.
I just push it in case it's useful to someone and to prevent double efforts.

Upgrade multihash

---

.travis.yml
Cargo.toml
README.md
src/error.rs
src/lib.rs
src/to_cid.rs

To me it's important to keep PRs related to a single thing. Though in this case it's six independent small things that can be reviewed on a commit by commit basis. They are so small that three independent PRs would mean way more overhead for reviewers.

Misc improvements

---

src/codec.rs
src/lib.rs
src/version.rs

...so you can use them in sorted collections

Add Ord instance for Cid

---

src/lib.rs
src/to_cid.rs

feat: Improve Cid::to_string_v0 and impl ToCid for str

---

Cargo.toml
src/error.rs
src/lib.rs
src/to_cid.rs

feat: use unsigned-varint instead of integer-encoding

---

src/cid.rs
src/prefix.rs
src/version.rs
tests/lib.rs

This is a PR with several changes, all of them small enough so that this review should be easy. They are also all in self-contained commits.
This concludes the work of porting over the changes I saw fit from https://github.com/multiformats/rust-cid/pull/18 (except for the CLI, that should be a separate PR).

Several minor changes

---

src/arb.rs

I broke master with merging https://github.com/multiformats/rust-cid/pull/24. This is a fix.

Fix master branch

---

src/codec.rs

feat: derive `Hash` trait for `Codec`

---

README.md

docs: fix example in README

---

Cargo.toml
src/cid.rs

Will not build until https://github.com/multiformats/rust-multihash/pull/67 is merged, published and bumped in here.
tl;dr you don't need these bounds.

remove unnecessary TryFrom error bounds

---

Cargo.toml

feat: update unsigned-varint to v0.5

---

.github/codecov.yml
.github/workflows/build.yml
.gitignore
Cargo.toml

Bump some deps & Improve gh actions

---

README.md

Update readme.md with the command on how to run tests.

add testing section to readme.md

---

Cargo.toml
src/arb.rs
src/cid.rs
src/lib.rs
tests/lib.rs

All the hard work is in Multihash. The change here is basically a large sed.

Implement const generics

---

Cargo.toml
src/cid.rs

Depends on https://github.com/multiformats/rust-multihash/pull/165

feat: constify some functions 

---

Cargo.toml
src/arb.rs

Depends on rust-multihash releasing

Add arbitrary::Arbitrary trait for Cid

---

src/cid.rs
src/error.rs
tests/lib.rs

Found by fuzzing in https://github.com/filecoin-project/ref-fvm/issues/676

Disallow explicit CIDv0

---

CHANGELOG.md

chore: prepare 0.10.1 release
