- Cargo.toml
- src/lib.rs
- src/to_cid.rs
Rationale: `varmint` fails to compile on non `x86_64` architectures.
> Replace varmint with integer-encoding crate

- Cargo.toml
Any chance to get a new version released to `crates.io`?
> Updating multihash to 0.6

- src/codec.rs
- src/error.rs
Pretty trivial spelling issue, but it tripped me up for longer than it should have 😅 
https://github.com/multiformats/rust-multihash and https://github.com/multiformats/rust-multibase also both have a similar misspelling. I can also submit a PR for those if you want.
> fix(spelling): UnkownCodec -> UnknownCodec

- Cargo.toml
Because of semver and the fact that multihash is unfortunately exposed in the API, this also requires bumping `cid` to 0.3.
> Bump multihash to 0.8

- src/to_cid.rs
- tests/lib.rs
by implementing `std::str::FromStr`
> Add support for `str::parse()`

- Cargo.toml
- src/error.rs
- src/lib.rs
- src/to_cid.rs
- src/version.rs
- tests/lib.rs
This PR currently depends on the unreleased version of `rust-multibase`
Fixes #19
> Upgrade multibase and multihash to support more encodings

- src/error.rs
Addresses warning I see when compiling this:
```
warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
--> src/error.rs:18:21
|
18 |         f.write_str(error::Error::description(self))
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
> Address deprecation warning

- Cargo.toml
The cargo-release crate did remove the docs update functionality
https://github.com/sunng87/cargo-release/commit/86429c581efee8177986bb5355c37c3c180b8ef8#diff-3abe220864dd3f76354817756e6ca3dc
> chore: doc uploading isn't a thing anymore

- README.md
- src/lib.rs
- src/to_cid.rs
- tests/lib.rs
...to benefit from inline storage, among other things
With this change, cloning a typical cid containing e.g. a 256 bit hash will not allocate and will therefore be much faster than before.
This also ensures that it is no longer possible to create a cid that contains an invalid multihash, where before you could pass just any byte array via the new method.
> Use multihash instance to store the hash

- src/cid.rs
- src/error.rs
- tests/lib.rs
It is now possible to create v0 CIDs via `Cid::new_v0()` and
v1 CIDs via `Cid:new_v0()`.
Credit goes to @dvc94ch as this code is based on
https://github.com/multiformats/rust-cid/pull/18
> feat: introduce dedicated methods for creating v0 and v1 CIDs

- Cargo.toml
- src/arb.rs
- src/lib.rs
Add arbitraries for Cid, Prefix and Codec
- the Codec arb prefers more popular codecs
> Add arbitraries

- Cargo.toml
The previous PR shouldn't have been merged before multihash isn't released.
This commit fixes it.
> fix: move to released versions

- src/cid.rs
- src/error.rs
- tests/lib.rs
Introduce `string_of_base()` method which enables the CID to be encoded
at different base encodings.
Example:
use cid::{Cid, Codec};
use multibase::Base;
use multihash::Sha2_256;
let cid = Cid::new_v1(Codec::Raw, Sha2_256::digest(b"foo"));
let encoded = cid.to_string_of_base(Base::Base64).unwrap();
assert_eq!(encoded, "mAVUSICwmtGto/8aP+ZtFPB0wQTQTQi1wZIO/oPmKXohiZueu");
> feat: make base encoding to other bases possible

- .github/workflows/build.yml
Always use the latest version of Tarpaulin for creating the coverage
report.
> chore: use latest version of Tarpaulin

- .github/workflows/build.yml
- Cargo.toml
- src/cid.rs
- src/error.rs
- src/lib.rs
- src/version.rs
- tests/lib.rs
It's now possible to use rust-cid with `no_std`.
This commit is based on @dvc94ch's work at
https://github.com/ipfs-rust/tiny-cid
The GitHub action for checkout no_std is based on
@svartalf's work at
https://github.com/svartalf/rust-macaddr/blob/0e89981f2fef6c5a431d38feff887a2762b104de/.github/workflows/ci.yml#L57-L81
BREAKING CHANGE: The `test` feature is now called `arb`.
> feat: make library no_std compatible

- src/cid.rs
- src/error.rs
- tests/lib.rs
This commit is based on @dvc94ch's work at https://github.com/ipfs-rust/tiny-cid
BREAKING CHANGE: The `Error` type no longer implements PartialEq, Eq, Clone, Copy.
The reason is that there is now also an IO error possible, which doesn't implement
those either.
> feat: introduce read_bytes() and write_bytes()

- Cargo.toml
- src/cid.rs
- src/version.rs
This PR is a collection of small changes (each commit is self-contained), which gets rust-cid to full feature parity with [tiny-cid](https://github.com/ipfs-rust/tiny-cid/).
> Changes for feature parity with tiny-cid

- Cargo.toml
- src/arb.rs
- src/cid.rs
- src/lib.rs
- tests/lib.rs
This PR upgrades to the latest version of `multihash` 0.13 and makes the `cid` API more similar with exporting `Cid` with a fixed size and `CidGeneric` which is generic over its size.
> Upgrade to multihash 0.13

- Cargo.toml
- src/cid.rs
- src/version.rs
This makes the `Hash` implementation of `Cid` no_std compatible.
BREAKING CHANGE: the hash is different from previous versions.
> feat: auto derive Hash impl

- src/cid.rs
This will just output e.g. 
`Cid(bafyreibjo4xmgaevkgud7mbifn3dzp4v4lyaui4yvqp3f2bqwtxcjrdqg4)`
instead of very verbose and mostly useless debug output like
`Cid { version: V1, codec: 113, hash: Multihash { code: 18, size: 32, digest: [150, 149, 13, 62, 149, 26, 108, 78, 7, 248, 174, 227, 218, 106, 245, 219, 248, 11, 78, 15, 207, 37, 223, 220, 224, 186, 29, 161, 245, 213, 248, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }`
The detailed debug output is still available using the alternate version, `{:#?}`
> Add manual debug instance

- .github/dependabot.yml
See https://dependabot.com/ for details on dependabot.
Part of the larger effort to switch rust-libp2p to upstream rust-multiaddr (https://github.com/libp2p/rust-libp2p/issues/758).
> .github/: Add dependabot

- README.md
- examples/readme.rs
Update the example in the README to work with the current version and
also add it as runnable example called `readme`:
cargo run --example readme
Closes #78.
> chore: Update example in README

- Cargo.toml
The release information is no longer compatible with newer versions
of cargo release, hence removing it.
> chore: remove custom release information

- .github/workflows/build.yml
- Cargo.toml
- src/serde.rs
Prior to this change, enabling the `serde-codec` flag wouldn't build without `std`.
> fix: make serde-codec build with no_std

- Cargo.toml
This also moves the "alloc" feature of serde, but that doesn't really matter.
Unfortunately, I can't find a good way to _test_ this.
> Only enable core2/alloc when alloc feature is enabled

- src/cid.rs
- tests/lib.rs
Simple conversion based on what other implementations do.
Should also help move https://github.com/multiformats/rust-cid/issues/59 along.
> feat: into_v1

- src/cid.rs
- tests/lib.rs
Not criticial but avoids possible correctness bugs.
Would have also cought the previous bug.
> Restrict length of Multihash for new_v0

- Cargo.toml
- src/serde.rs
The minimum supported Rust version is set to 1.60 due to the `parity-scale-codec` dependency.
BREAKING CHANGE: Rust edition 2021 is now used
---
As https://github.com/multiformats/rust-cid/pull/129 will be a breaking change, it makes sense to bundle them in one release, hence I propose doing a Rust edition 2021 upgrade here.
> chore: upgrade to Rust edition 2021 and set MSRV

- Cargo.toml
- src/cid.rs
Depends on https://github.com/multiformats/rust-multihash/pull/252
> feat: add `encoded_len` and written bytes

- CHANGELOG.md
- RELEASE.md
This commit finally starts to add a changelog.
@Stebalien I know you hate breaking change releases (me too), this will hopefully be the last breaking one for a longer period of time. It's needed for https://github.com/ipld/libipld/pull/170.
> chore: add changelog for v0.10.0 release

- Cargo.toml
The `arb` feature of CID requires the default code table of `multihash`, hence the `multihash-impl` feature of `multihash` needs to be enabled.
This fixes a build failure in libipld.
> fix: the arb feature needs more multihash features

- Cargo.toml
- examples/readme.rs
- src/arb.rs
- src/cid.rs
- src/lib.rs
- tests/lib.rs
> Update to multihash 0.19

- Cargo.toml
- src/arb.rs
- src/cid.rs
> Make `multihash-codetable` a dev-dependency

- README.md
- examples/readme.rs
- src/cid.rs
- tests/lib.rs
The goal of this pull request is to refactor `unwrap()` to return the `u64` value or an`Error:VarIntDecodeError` in the `no_std` environment.
This error was discovered in fuzz testing.
Tests were refactored to include a new `no_std_tests` module, in order to test the fix. 
`cargo test --no-default-features` will execute the `no_std` test.
> `varint_read_u64` panics on unwrap in `no_std` environment

- .github/workflows/build.yml
- tests/lib.rs
Also run the no_std tests on CI.
> test: don't require alloc for no_std test

- CHANGELOG.md
Update the changelog.
---
As this is a breaking change (due to upgrading multihash), this is the chance to comment if someone wants more breaking changes in. Once this PR is merged, I'll cut a release.
> chore: prepare the v0.11.0 release

- CHANGELOG.md
With this new release it's possible to specify `serde` instead of `serde-codec` as feature.
---
@Stebalien if you approve that PR, you also approve that I cut the release right after this is merged.
> chore: prepare v0.11.1 release

- Cargo.toml
Hi! While scraping crates.io I've found this crate to be missing the `repository` attribute in Cargo.toml. This attribute makes it easy for users and scrapers, including security tools, to find about the repository behind a crate. I've decided to replace the `homepage` attribute with `repository` as that is the more common choice among crates.
> Replace homepage attribute with repository in Cargo.toml

- src/arb.rs
When compiled with no default features, but the `arb` feature disabled, the compilation fails. With this change it's now possible.
> fix: make arb feature work with no-std

- Cargo.toml
To fix https://github.com/multiformats/rust-cid/actions/runs/11854518907/job/33036842910?pr=164#step:6:142
```
warning: current MSRV (Minimum Supported Rust Version) is `1.60.0` but this item is stable since `1.63.0`
--> src/arb.rs:26:24
|
26 |             let data = core::array::from_fn::<_, 32, _>(|_| u8::arbitrary(g));
|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
= note: `#[warn(clippy::incompatible_msrv)]` on by default
```
> chore: bump msrv to 1.63

- README.md
We always forget to update it. Instead, document how to add the dependency with `cargo add`.
Also, remove the documentation around how to test the README example, it no longer works and the README is now tested as a part of the main test suite.
> doc: don't document crate version in the readme

- .github/workflows/build.yml
- Cargo.toml
- rust-toolchain.toml
1. Test on the MSRV.
2. Use `rust-toolchain.toml` to specify the default compiler.
3. Update the MSRV to 1.81 to match our dependencies.
> Update MSRV to 1.81, specify toolchain, and fix CI
